arena:
  workstations:
    SH01: "SH"
    WS02: "10"
    WS03: "10"
    WS04: "00"
    PP01: "PP"
    TT01: "TT"
    WS07: "05"
    WS08: "05"
    WS09: "15"
    WS10: "05"
    WS11: "05"
    WS12: "00"
    WS13: "00"
    WS14: "10"
    WS15: "10"
    SH01: "SH"
    WS17: "15"
    WS18: "15"
  objects:
    F20_20_G      : 10
    F20_20_B      : 10
    S40_40_B      : 10
    S40_40_G      : 10
    M20           : 2
    M30           : 10
    M20_100       : 10
    R20           : 10
    AXIS          : 10
    BEARING       : 10
    BEARING_BOX   : 10
    DISTANCE_TUBE : 10
    MOTOR         : 10
    CONTAINER_RED :  2
    CONTAINER_BLUE:  2
  cavities: [ "F20_20_H", "S40_40_H", "M20_H", "M30_H", "M20_100_H", "R20_H", "F20_20_V", "S40_40_V", "M20_V", "M30_V", "R20_V" ]
